<?php

return [
    'fallback' => 'extension',

    'modules' => [
        'banner' => 'panorama',
        'banners' => 'panorama',
        'catalog' => 'inventory_2',
        'catalogus' => 'inventory_2',
        'catalog-products' => 'inventory_2',
        'commerce' => 'shopping_bag',
        'configuration' => 'settings',
        'content' => 'article',
        'countries' => 'public',
        'domein' => 'domain',
        'download' => 'download',
        'downloads' => 'download',
        'evenementen' => 'event',
        'events' => 'event',
        'faq' => 'quiz',
        'form' => 'dynamic_form',
        'forms' => 'dynamic_form',
        'landen' => 'public',
        'language' => 'translate',
        'languages' => 'translate',
        'localization' => 'language',
        'locations' => 'store',
        'media' => 'perm_media',
        'merken' => 'sell',
        'module' => 'extension',
        'modules' => 'extension',
        'redirect' => 'route',
        'redirects' => 'route',
        'roles' => 'admin_panel_settings',
        'rollen' => 'admin_panel_settings',
        'settings' => 'settings',
        'subdomains' => 'lan',
        'translations' => 'translate',
        'templates' => 'dashboard_customize',
        'url' => 'link',
        'urlverwijzingen' => 'link',
        'users' => 'group',
        'vacatures' => 'work',
        'vestigingen' => 'store',
        'website' => 'language',
        'website-templates' => 'dashboard_customize',
    ],

    'screens' => [
        'banner-categories' => 'category',
        'banners' => 'panorama',
        'catalog-brands' => 'sell',
        'catalog-categories' => 'account_tree',
        'catalog-products' => 'inventory_2',
        'content-categories' => 'folder_copy',
        'content-items' => 'article',
        'countries' => 'public',
        'domains' => 'domain',
        'download-categories' => 'folder_zip',
        'downloads' => 'download',
        'event-categories' => 'event_list',
        'events' => 'event',
        'faq-categories' => 'quiz',
        'faq-items' => 'help_center',
        'form-categories' => 'fact_check',
        'forms' => 'dynamic_form',
        'location-categories' => 'map',
        'locations' => 'store',
        'navigation' => 'account_tree',
        'redirects' => 'route',
        'roles' => 'admin_panel_settings',
        'translations' => 'translate',
        'url-references' => 'link',
        'urls' => 'add_link',
        'user-categories' => 'groups',
        'users' => 'person',
        'vacancies' => 'work',
        'vacancy-categories' => 'workspaces',
        'website-templates' => 'dashboard_customize',
    ],
];
