<?php

return [
    'fallback' => 'extension',

    'modules' => [
        'actiecodes' => 'confirmation_number',
        'afleverdata' => 'local_shipping',
        'banner' => 'panorama',
        'banners' => 'panorama',
        'betaalmethoden' => 'payments',
        'catalog' => 'inventory_2',
        'catalogus' => 'inventory_2',
        'catalog-products' => 'inventory_2',
        'content' => 'article',
        'countries' => 'public',
        'domein' => 'domain',
        'download' => 'download',
        'downloads' => 'download',
        'evenementen' => 'event',
        'events' => 'event',
        'faq' => 'quiz',
        'form' => 'dynamic_form',
        'forms' => 'dynamic_form',
        'gastenboek' => 'menu_book',
        'guestbook' => 'menu_book',
        'landen' => 'public',
        'languages' => 'translate',
        'locations' => 'store',
        'merken' => 'sell',
        'module' => 'extension',
        'modules' => 'extension',
        'newsletter' => 'mark_email_read',
        'orders' => 'shopping_basket',
        'promotie' => 'campaign',
        'redirect' => 'route',
        'redirects' => 'route',
        'review' => 'rate_review',
        'reviews' => 'rate_review',
        'roles' => 'admin_panel_settings',
        'rollen' => 'admin_panel_settings',
        'settings' => 'settings',
        'slider' => 'view_carousel',
        'sliders' => 'view_carousel',
        'subdomains' => 'lan',
        'translations' => 'translate',
        'templates' => 'dashboard_customize',
        'url' => 'link',
        'urlverwijzingen' => 'link',
        'users' => 'group',
        'vacatures' => 'work',
        'vestigingen' => 'store',
        'website' => 'language',
        'website-templates' => 'dashboard_customize',
    ],
];
