<?php

$groups = [
    'content' => 'Content',
    'commerce' => 'Commerce',
    'media' => 'Media',
    'users' => 'Users',
    'locations' => 'Locations',
    'events' => 'Events',
    'seo' => 'SEO',
    'modules' => 'Modules',
    'configuration' => 'Configuration',
    'localization' => 'Localization',
    'platform' => 'Platform',
    'website' => 'Website',
];

$modules = [
    'content' => [
        'name' => 'Content',
        'legacy_path' => 'cms/content',
        'group' => 'content',
        'table' => 'content_items',
        'title_column' => 'title',
        'description' => 'Pages, content categories, blocks, images, and attachments.',
        'legacy_tables' => ['contentitems', 'contentcategorieen', 'contentitemblock', 'contentitemafbeeldingen', 'contentitemattachment'],
    ],
    'banners' => [
        'name' => 'Banners',
        'legacy_path' => 'cms/banner',
        'group' => 'media',
        'table' => 'banners',
        'title_column' => 'title',
        'description' => 'Banner images, categories, and translations.',
        'legacy_tables' => ['banner', 'bannercategorie', 'bannerbannercategorie', 'bannertranslation'],
    ],
    'sliders' => [
        'name' => 'Sliders',
        'legacy_path' => 'cms/slider',
        'group' => 'media',
        'table' => 'sliders',
        'title_column' => 'title',
        'description' => 'Slider images, categories, links, and display windows.',
        'legacy_tables' => ['slider', 'slidercategorie', 'sliderslidercategorie'],
    ],
    'forms' => [
        'name' => 'Forms',
        'legacy_path' => 'cms/form',
        'group' => 'content',
        'table' => 'forms',
        'title_column' => 'name',
        'description' => 'Form builder blocks, rows, fields, options, messages, and submissions.',
        'legacy_tables' => ['form', 'formcategorie', 'formfield', 'formmessage', 'formulier'],
    ],
    'events' => [
        'name' => 'Events',
        'legacy_path' => 'cms/evenementen',
        'group' => 'events',
        'table' => 'events',
        'title_column' => 'title',
        'description' => 'Events, event categories, parts, images, and attachments.',
        'legacy_tables' => ['evenement', 'evenementcategorieen', 'evenementonderdeel', 'evenementafbeeldingen', 'evenementattachment'],
    ],
    'faq' => [
        'name' => 'FAQ',
        'legacy_path' => 'cms/faq',
        'group' => 'content',
        'table' => 'faq_items',
        'title_column' => 'question',
        'description' => 'Frequently asked questions, categories, images, videos, and attachments.',
        'legacy_tables' => ['faq', 'faqcategorie', 'faqafbeeldingen', 'faqattachment', 'faqvideo'],
    ],
    'downloads' => [
        'name' => 'Downloads',
        'legacy_path' => 'cms/download',
        'group' => 'modules',
        'table' => 'downloads',
        'title_column' => 'name',
        'description' => 'Download files and download categories.',
        'legacy_tables' => ['downloads', 'downloadcategorieen', 'downloaddownloadcategorie'],
    ],
    'locations' => [
        'name' => 'Locations',
        'legacy_path' => 'cms/vestigingen',
        'group' => 'locations',
        'table' => 'locations',
        'title_column' => 'name',
        'description' => 'Locations, categories, images, opening hours, and special opening hours.',
        'legacy_tables' => ['vestiging', 'vestigingcategorie', 'vestigingopeningstijd', 'vestigingspecialeopeningstijd'],
    ],
    'vacancies' => [
        'name' => 'Vacancies',
        'legacy_path' => 'cms/vacatures',
        'group' => 'content',
        'table' => 'vacancies',
        'title_column' => 'title',
        'description' => 'Vacancies, vacancy categories, and attachments.',
        'legacy_tables' => ['vacatures', 'vacaturecategorieen', 'vacatureattachment'],
    ],
    'catalog' => [
        'name' => 'Catalog',
        'legacy_path' => 'cms/catalogus',
        'group' => 'commerce',
        'table' => 'catalog_products',
        'title_column' => 'name',
        'description' => 'Products, categories, brands, promotions, discounts, media, stock, reviews, and product options.',
        'legacy_tables' => ['catalogusartikel', 'cataloguscategorie', 'catalogusmerk', 'cataloguspromotie', 'catalogusreview', 'actiecode'],
    ],
    'orders' => [
        'name' => 'Orders',
        'legacy_path' => 'cms/orders',
        'group' => 'commerce',
        'table' => 'orders',
        'title_column' => 'order_number',
        'description' => 'Orders, order lines, delivery dates, and delivery settings.',
        'legacy_tables' => ['orders', 'orderregels', 'orderafleverdata', 'orderafleverdatadag', 'orderafleverdatadatum'],
    ],
    'seo' => [
        'name' => 'SEO',
        'legacy_path' => 'cms/redirect',
        'group' => 'seo',
        'table' => 'redirects',
        'title_column' => 'source_path',
        'description' => 'Redirects, URL registry, and URL references.',
        'legacy_tables' => ['redirect', 'url', 'urlverwijzing'],
    ],
    'users' => [
        'name' => 'Users',
        'legacy_path' => 'cms/users',
        'group' => 'users',
        'table' => 'users',
        'title_column' => 'name',
        'description' => 'Users, user categories, sessions, login tracking, cookies, and reset tokens.',
        'legacy_tables' => ['users', 'usercategorieen', 'userlogins', 'usersession', 'resetpassword', 'token'],
    ],
    'roles' => [
        'name' => 'Roles and Permissions',
        'legacy_path' => 'cms/roles',
        'group' => 'configuration',
        'table' => 'roles',
        'title_column' => 'name',
        'description' => 'Laravel-managed roles with permissions per module, field, and module block.',
        'legacy_tables' => ['role', 'permissions', 'rechten', 'rechtencategoriespecificatie'],
    ],
    'module_manager' => [
        'name' => 'Module Manager',
        'legacy_path' => 'cms/module',
        'group' => 'configuration',
        'table' => 'cms_modules',
        'title_column' => 'name',
        'read_only' => true,
        'description' => 'Base and website module registration, categories, and sort order.',
        'legacy_tables' => ['module', 'modulecategorie', 'modulemodulecategorie'],
    ],
    'countries' => [
        'name' => 'Countries',
        'legacy_path' => 'cms/isolanden',
        'group' => 'configuration',
        'table' => 'countries',
        'title_column' => 'name',
        'description' => 'Package-backed countries, website languages, ISO language data, and payment-country settings.',
        'legacy_tables' => ['isolanden', 'isolandcode', 'isolandbetalingswijze', 'landen', 'isotalen', 'talen'],
    ],
    'translations' => [
        'name' => 'Translations',
        'legacy_path' => 'cms/translations',
        'group' => 'localization',
        'table' => 'translation_keys',
        'title_column' => 'key',
        'description' => 'Translation keys, values, source strings, and runtime translations.',
        'legacy_tables' => ['translatekey', 'translatecontent', 'translation'],
    ],
    'guestbook' => [
        'name' => 'Guestbook',
        'legacy_path' => 'cms/gastenboek',
        'group' => 'website',
        'table' => 'guestbook_entries',
        'title_column' => 'author_name',
        'description' => 'Guestbook messages and publication status.',
        'legacy_tables' => ['gastenboek'],
    ],
];

$screens = [
    'content_items' => [
        'name' => 'Content',
        'legacy_path' => 'cms/content',
        'group' => 'content',
        'table' => 'content_items',
        'title_column' => 'title',
        'description' => 'Legacy content item overview and editor.',
        'legacy_tables' => ['contentitems'],
        'pages' => [
            'index' => ['name' => 'Content overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit content item', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Content images', 'type' => 'edit', 'table' => 'content_images', 'title_column' => 'caption', 'legacy_tables' => ['contentitemafbeeldingen']],
            'editSlider' => ['name' => 'Content slider', 'type' => 'edit', 'table' => 'sliders', 'title_column' => 'title', 'legacy_tables' => ['slider']],
        ],
    ],
    'content_categories' => [
        'name' => 'Content Categories',
        'legacy_path' => 'cms/content/categorieen',
        'group' => 'content',
        'table' => 'content_categories',
        'title_column' => 'name',
        'description' => 'Legacy content category tree and editor.',
        'legacy_tables' => ['contentcategorieen', 'contentcategorieafbeeldingen'],
        'pages' => [
            'index' => ['name' => 'Category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit content category', 'type' => 'edit'],
            'editSlider' => ['name' => 'Category slider', 'type' => 'edit', 'table' => 'sliders', 'title_column' => 'title', 'legacy_tables' => ['slider']],
        ],
    ],
    'events' => [
        'name' => 'Events',
        'legacy_path' => 'cms/evenementen',
        'group' => 'events',
        'table' => 'events',
        'title_column' => 'title',
        'description' => 'Legacy events overview and editor.',
        'legacy_tables' => ['evenement'],
        'pages' => [
            'index' => ['name' => 'Events overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit event', 'type' => 'edit'],
        ],
    ],
    'event_categories' => [
        'name' => 'Event Categories',
        'legacy_path' => 'cms/evenementen/categorieen',
        'group' => 'events',
        'table' => 'event_categories',
        'title_column' => 'name',
        'description' => 'Legacy event category overview and editor.',
        'legacy_tables' => ['evenementcategorieen'],
        'pages' => [
            'index' => ['name' => 'Event category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit event category', 'type' => 'edit'],
        ],
    ],
    'faq_items' => [
        'name' => 'FAQ',
        'legacy_path' => 'cms/faq',
        'group' => 'content',
        'table' => 'faq_items',
        'title_column' => 'question',
        'description' => 'Legacy FAQ overview and editor.',
        'legacy_tables' => ['faq'],
        'pages' => [
            'index' => ['name' => 'FAQ overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit FAQ item', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'FAQ images', 'type' => 'edit', 'table' => 'faq_images', 'title_column' => 'caption', 'legacy_tables' => ['faqafbeeldingen']],
            'editVideo' => ['name' => 'FAQ videos', 'type' => 'edit', 'table' => 'faq_videos', 'title_column' => 'title', 'legacy_tables' => ['faqvideo']],
        ],
    ],
    'faq_categories' => [
        'name' => 'FAQ Categories',
        'legacy_path' => 'cms/faq/categorieen',
        'group' => 'content',
        'table' => 'faq_categories',
        'title_column' => 'name',
        'description' => 'Legacy FAQ category overview and editor.',
        'legacy_tables' => ['faqcategorie'],
        'pages' => [
            'index' => ['name' => 'FAQ category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit FAQ category', 'type' => 'edit'],
        ],
    ],
    'forms' => [
        'name' => 'Forms',
        'legacy_path' => 'cms/form',
        'group' => 'content',
        'table' => 'forms',
        'title_column' => 'name',
        'description' => 'Legacy form builder overview and editor.',
        'legacy_tables' => ['form'],
        'pages' => [
            'index' => ['name' => 'Forms overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit form', 'type' => 'edit'],
            'editMessages' => ['name' => 'Form messages', 'type' => 'edit', 'table' => 'form_messages', 'title_column' => 'subject', 'legacy_tables' => ['formmessage']],
        ],
    ],
    'form_categories' => [
        'name' => 'Form Categories',
        'legacy_path' => 'cms/form/categorieen',
        'group' => 'content',
        'table' => 'form_categories',
        'title_column' => 'name',
        'description' => 'Legacy form category overview and editor.',
        'legacy_tables' => ['formcategorie'],
        'pages' => [
            'index' => ['name' => 'Form category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit form category', 'type' => 'edit'],
        ],
    ],
    'vacancies' => [
        'name' => 'Vacancies',
        'legacy_path' => 'cms/vacatures',
        'group' => 'content',
        'table' => 'vacancies',
        'title_column' => 'title',
        'description' => 'Legacy vacancy overview and editor.',
        'legacy_tables' => ['vacatures'],
        'pages' => [
            'index' => ['name' => 'Vacancy overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit vacancy', 'type' => 'edit'],
        ],
    ],
    'vacancy_categories' => [
        'name' => 'Vacancy Categories',
        'legacy_path' => 'cms/vacatures/categorieen',
        'group' => 'content',
        'table' => 'vacancy_categories',
        'title_column' => 'name',
        'description' => 'Legacy vacancy category overview and editor.',
        'legacy_tables' => ['vacaturecategorieen'],
        'pages' => [
            'index' => ['name' => 'Vacancy category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit vacancy category', 'type' => 'edit'],
        ],
    ],
    'banners' => [
        'name' => 'Banners',
        'legacy_path' => 'cms/banner',
        'group' => 'media',
        'table' => 'banners',
        'title_column' => 'title',
        'description' => 'Legacy banner overview, editor, and bulk upload screen.',
        'legacy_tables' => ['banner'],
        'pages' => [
            'index' => ['name' => 'Banners overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit banner', 'type' => 'edit'],
            'bulkUploader' => ['name' => 'Bulk banner uploader', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'banner_categories' => [
        'name' => 'Banner Categories',
        'legacy_path' => 'cms/banner/categorieen',
        'group' => 'media',
        'table' => 'banner_categories',
        'title_column' => 'name',
        'description' => 'Legacy banner category overview and editor.',
        'legacy_tables' => ['bannercategorie'],
        'pages' => [
            'index' => ['name' => 'Banner category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit banner category', 'type' => 'edit'],
        ],
    ],
    'sliders' => [
        'name' => 'Sliders',
        'legacy_path' => 'cms/slider',
        'group' => 'media',
        'table' => 'sliders',
        'title_column' => 'title',
        'description' => 'Legacy slider overview and editor.',
        'legacy_tables' => ['slider'],
        'pages' => [
            'index' => ['name' => 'Slider overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit slider', 'type' => 'edit'],
        ],
    ],
    'slider_categories' => [
        'name' => 'Slider Categories',
        'legacy_path' => 'cms/slider/categorieen',
        'group' => 'media',
        'table' => 'slider_categories',
        'title_column' => 'name',
        'description' => 'Legacy slider category overview and editor.',
        'legacy_tables' => ['slidercategorie'],
        'pages' => [
            'index' => ['name' => 'Slider category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit slider category', 'type' => 'edit'],
        ],
    ],
    'catalog_products' => [
        'name' => 'Catalog Products',
        'legacy_path' => 'cms/catalogus',
        'group' => 'commerce',
        'table' => 'catalog_products',
        'title_column' => 'name',
        'description' => 'Legacy catalog product overview and editor.',
        'legacy_tables' => ['catalogusartikel'],
        'pages' => [
            'index' => ['name' => 'Catalog product overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog product', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Product images', 'type' => 'edit', 'table' => 'catalog_product_images', 'title_column' => 'caption', 'legacy_tables' => ['catalogusartikelafbeelding']],
            'editCombinaties' => ['name' => 'Product combinations', 'type' => 'edit', 'table' => 'catalog_product_combinations', 'title_column' => 'catalog_product_id', 'legacy_tables' => ['cataloguscombinatie']],
            'editOptions' => ['name' => 'Product options', 'type' => 'edit', 'table' => 'catalog_product_options', 'title_column' => 'label', 'legacy_tables' => ['catalogusartikeloption']],
            'editVertalingen' => ['name' => 'Product translations', 'type' => 'edit', 'table' => 'catalog_product_translations', 'title_column' => 'title', 'legacy_tables' => ['catalogusvertaling']],
            'editVideo' => ['name' => 'Product videos', 'type' => 'edit', 'table' => 'catalog_product_videos', 'title_column' => 'title', 'legacy_tables' => ['catalogusvideo']],
            'editVoorraad' => ['name' => 'Product stock', 'type' => 'edit', 'table' => 'catalog_stock', 'title_column' => 'catalog_product_id', 'legacy_tables' => ['catalogusvoorraad']],
            'resetSortIndex' => ['name' => 'Reset product sort order', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'catalog_categories' => [
        'name' => 'Catalog Categories',
        'legacy_path' => 'cms/catalogus/categorieen',
        'group' => 'commerce',
        'table' => 'catalog_categories',
        'title_column' => 'name',
        'description' => 'Legacy catalog category overview and editor.',
        'legacy_tables' => ['cataloguscategorie'],
        'pages' => [
            'index' => ['name' => 'Catalog category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog category', 'type' => 'edit'],
        ],
    ],
    'catalog_brands' => [
        'name' => 'Catalog Brands',
        'legacy_path' => 'cms/catalogus/merken',
        'group' => 'commerce',
        'table' => 'catalog_brands',
        'title_column' => 'name',
        'description' => 'Legacy catalog brand overview and editor.',
        'legacy_tables' => ['catalogusmerk'],
        'pages' => [
            'index' => ['name' => 'Catalog brand overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog brand', 'type' => 'edit'],
        ],
    ],
    'catalog_promotions' => [
        'name' => 'Catalog Promotions',
        'legacy_path' => 'cms/catalogus/promotie',
        'group' => 'commerce',
        'table' => 'catalog_promotions',
        'title_column' => 'name',
        'description' => 'Legacy catalog promotion overview and editor.',
        'legacy_tables' => ['cataloguspromotie'],
        'pages' => [
            'index' => ['name' => 'Catalog promotion overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog promotion', 'type' => 'edit'],
        ],
    ],
    'catalog_reviews' => [
        'name' => 'Catalog Reviews',
        'legacy_path' => 'cms/catalogus/review',
        'group' => 'commerce',
        'table' => 'catalog_reviews',
        'title_column' => 'title',
        'description' => 'Legacy catalog review overview and editor.',
        'legacy_tables' => ['catalogusreview'],
        'pages' => [
            'index' => ['name' => 'Catalog review overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog review', 'type' => 'edit'],
        ],
    ],
    'catalog_coupons' => [
        'name' => 'Action Codes',
        'legacy_path' => 'cms/catalogus/actiecodes',
        'group' => 'commerce',
        'table' => 'catalog_coupons',
        'title_column' => 'name',
        'description' => 'Legacy action code overview and editor.',
        'legacy_tables' => ['actiecode'],
        'pages' => [
            'index' => ['name' => 'Action code overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit action code', 'type' => 'edit'],
        ],
    ],
    'orders' => [
        'name' => 'Orders',
        'legacy_path' => 'cms/orders',
        'group' => 'commerce',
        'table' => 'orders',
        'title_column' => 'order_number',
        'description' => 'Legacy order overview, editor, documents, and cart detail pages.',
        'legacy_tables' => ['orders'],
        'pages' => [
            'index' => ['name' => 'Order overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit order', 'type' => 'edit'],
            'action' => ['name' => 'Order action', 'type' => 'utility', 'read_only' => true],
            'cartlist' => ['name' => 'Order item list', 'type' => 'utility', 'table' => 'order_items', 'title_column' => 'name', 'read_only' => true, 'legacy_tables' => ['orderregels']],
            'carttotals' => ['name' => 'Order totals', 'type' => 'utility', 'read_only' => true],
            'downloadfactuur' => ['name' => 'Download invoice', 'type' => 'utility', 'read_only' => true],
            'downloadpakbon' => ['name' => 'Download packing slip', 'type' => 'utility', 'read_only' => true],
            'generateAdresSticker' => ['name' => 'Generate address sticker', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'order_delivery_dates' => [
        'name' => 'Delivery Dates',
        'legacy_path' => 'cms/orders/afleverdata',
        'group' => 'commerce',
        'table' => 'delivery_dates',
        'title_column' => 'date',
        'description' => 'Legacy delivery date overview and editor.',
        'legacy_tables' => ['orderafleverdata', 'orderafleverdatadag', 'orderafleverdatadatum'],
        'pages' => [
            'index' => ['name' => 'Delivery date overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit delivery date', 'type' => 'edit'],
        ],
    ],
    'order_payment_methods' => [
        'name' => 'Payment Methods',
        'legacy_path' => 'cms/orders/betaalmethoden',
        'group' => 'commerce',
        'table' => 'country_payment_methods',
        'title_column' => 'country_id',
        'description' => 'Legacy country payment method overview.',
        'legacy_tables' => ['isolandbetalingswijze'],
        'pages' => [
            'index' => ['name' => 'Payment method overview', 'type' => 'index'],
        ],
    ],
    'order_exports' => [
        'name' => 'Order Export',
        'legacy_path' => 'cms/orders/export',
        'group' => 'commerce',
        'table' => 'orders',
        'title_column' => 'order_number',
        'read_only' => true,
        'description' => 'Legacy order export screens.',
        'legacy_tables' => ['orders'],
        'pages' => [
            'index' => ['name' => 'Order export overview', 'type' => 'utility', 'read_only' => true],
            'generateExcel' => ['name' => 'Generate order export', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'users' => [
        'name' => 'Users',
        'legacy_path' => 'cms/users',
        'group' => 'users',
        'table' => 'users',
        'title_column' => 'name',
        'description' => 'Laravel users enhanced with legacy CMS profile fields, categories, active windows, and roles.',
        'legacy_tables' => ['users'],
        'pages' => [
            'index' => ['name' => 'User overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit user', 'type' => 'edit'],
            'resetPassword' => ['name' => 'Reset user password', 'type' => 'utility', 'read_only' => true],
            'wachtwoordvergeten' => ['name' => 'Forgotten password', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'user_categories' => [
        'name' => 'User Categories',
        'legacy_path' => 'cms/users/categorieen',
        'group' => 'users',
        'table' => 'user_categories',
        'title_column' => 'name',
        'description' => 'Legacy user category overview and editor.',
        'legacy_tables' => ['usercategorieen'],
        'pages' => [
            'index' => ['name' => 'User category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit user category', 'type' => 'edit'],
        ],
    ],
    'locations' => [
        'name' => 'Locations',
        'legacy_path' => 'cms/vestigingen',
        'group' => 'locations',
        'table' => 'locations',
        'title_column' => 'name',
        'description' => 'Legacy location overview and editor.',
        'legacy_tables' => ['vestiging'],
        'pages' => [
            'index' => ['name' => 'Location overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit location', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Location images', 'type' => 'edit', 'table' => 'location_images', 'title_column' => 'caption', 'legacy_tables' => ['vestigingafbeeldingen']],
            'editOpeningstijden' => ['name' => 'Location opening hours', 'type' => 'edit', 'table' => 'location_opening_hours', 'title_column' => 'day', 'legacy_tables' => ['vestigingopeningstijd', 'vestigingspecialeopeningstijd']],
        ],
    ],
    'location_categories' => [
        'name' => 'Location Categories',
        'legacy_path' => 'cms/vestigingen/categorieen',
        'group' => 'locations',
        'table' => 'location_categories',
        'title_column' => 'name',
        'description' => 'Legacy location category overview and editor.',
        'legacy_tables' => ['vestigingcategorie'],
        'pages' => [
            'index' => ['name' => 'Location category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit location category', 'type' => 'edit'],
        ],
    ],
    'redirects' => [
        'name' => 'Redirects',
        'legacy_path' => 'cms/redirect',
        'group' => 'seo',
        'table' => 'redirects',
        'title_column' => 'source_path',
        'description' => 'Legacy redirect overview and editor.',
        'legacy_tables' => ['redirect'],
        'pages' => [
            'index' => ['name' => 'Redirect overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit redirect', 'type' => 'edit'],
        ],
    ],
    'urls' => [
        'name' => 'URLs',
        'legacy_path' => 'cms/url',
        'group' => 'seo',
        'table' => 'urls',
        'title_column' => 'path',
        'description' => 'Legacy URL registry overview and editor.',
        'legacy_tables' => ['url'],
        'pages' => [
            'index' => ['name' => 'URL overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit URL', 'type' => 'edit'],
        ],
    ],
    'url_references' => [
        'name' => 'URL References',
        'legacy_path' => 'cms/urlverwijzingen',
        'group' => 'seo',
        'table' => 'url_references',
        'title_column' => 'source_path',
        'description' => 'Legacy URL reference overview and editor.',
        'legacy_tables' => ['urlverwijzing'],
        'pages' => [
            'index' => ['name' => 'URL reference overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit URL reference', 'type' => 'edit'],
        ],
    ],
    'downloads' => [
        'name' => 'Downloads',
        'legacy_path' => 'cms/download',
        'group' => 'modules',
        'table' => 'downloads',
        'title_column' => 'name',
        'description' => 'Legacy download overview and editor.',
        'legacy_tables' => ['downloads'],
        'pages' => [
            'index' => ['name' => 'Download overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit download', 'type' => 'edit'],
        ],
    ],
    'download_categories' => [
        'name' => 'Download Categories',
        'legacy_path' => 'cms/download/categorieen',
        'group' => 'modules',
        'table' => 'download_categories',
        'title_column' => 'name',
        'description' => 'Legacy download category overview and editor.',
        'legacy_tables' => ['downloadcategorieen'],
        'pages' => [
            'index' => ['name' => 'Download category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit download category', 'type' => 'edit'],
        ],
    ],
    'module_manager' => [
        'name' => 'Module Manager',
        'legacy_path' => 'cms/module',
        'group' => 'configuration',
        'table' => 'cms_modules',
        'title_column' => 'name',
        'read_only' => true,
        'description' => 'Legacy module overview and protected editor.',
        'legacy_tables' => ['module'],
        'pages' => [
            'index' => ['name' => 'Module overview', 'type' => 'index', 'read_only' => true],
            'edit' => ['name' => 'Edit module', 'type' => 'edit', 'read_only' => true],
        ],
    ],
    'module_categories' => [
        'name' => 'Module Categories',
        'legacy_path' => 'cms/module/categorieen',
        'group' => 'configuration',
        'table' => 'module_categories',
        'title_column' => 'name',
        'description' => 'Legacy module category overview and editor.',
        'legacy_tables' => ['modulecategorie'],
        'pages' => [
            'index' => ['name' => 'Module category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit module category', 'type' => 'edit'],
        ],
    ],
    'roles' => [
        'name' => 'Roles and Permissions',
        'legacy_path' => 'cms/roles',
        'group' => 'configuration',
        'table' => 'roles',
        'title_column' => 'name',
        'description' => 'Laravel role and permission overview with module, field, and block permissions.',
        'legacy_tables' => ['role', 'rechten'],
        'pages' => [
            'index' => ['name' => 'Role overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit role', 'type' => 'edit'],
        ],
    ],
    'domains' => [
        'name' => 'Domains',
        'legacy_path' => 'cms/domein',
        'group' => 'configuration',
        'table' => 'domains',
        'title_column' => 'host',
        'description' => 'Legacy domain overview and editor.',
        'legacy_tables' => ['domein'],
        'pages' => [
            'index' => ['name' => 'Domain overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit domain', 'type' => 'edit'],
        ],
    ],
    'countries' => [
        'name' => 'Countries',
        'legacy_path' => 'cms/isolanden',
        'group' => 'configuration',
        'table' => 'countries',
        'title_column' => 'name',
        'description' => 'Package-backed country overview, country editor, and website language settings.',
        'legacy_tables' => ['isolanden', 'isotalen', 'talen'],
        'pages' => [
            'index' => ['name' => 'Country overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit country', 'type' => 'edit'],
            'talen' => ['name' => 'Website languages', 'type' => 'index'],
        ],
    ],
    'translations' => [
        'name' => 'Translations',
        'legacy_path' => 'cms/translations',
        'group' => 'localization',
        'table' => 'translation_keys',
        'title_column' => 'key',
        'description' => 'Backend and frontend translation key overview and editor.',
        'legacy_tables' => ['translatekey', 'translatecontent', 'translation'],
        'pages' => [
            'index' => ['name' => 'Translation overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit translation', 'type' => 'edit'],
            'sync' => ['name' => 'Synchronize translations', 'type' => 'utility'],
        ],
    ],
];

$rootPages = [
    'dashboard' => ['name' => 'Dashboard', 'type' => 'dashboard'],
    'firstLogin' => ['name' => 'First login', 'type' => 'utility'],
    'resetpass' => ['name' => 'Reset password', 'type' => 'utility'],
    'token' => ['name' => 'Token login', 'type' => 'utility'],
    'delete' => ['name' => 'Delete record', 'type' => 'utility'],
];

$legacyClasses = [
    'Actiecode' => 'catalog_coupons',
    'Banner' => 'banners',
    'BannerCategorie' => 'banner_categories',
    'CatalogusArtikel' => 'catalog_products',
    'CatalogusCategorie' => 'catalog_categories',
    'CatalogusMerk' => 'catalog_brands',
    'CatalogusPromotie' => 'catalog_promotions',
    'ContentCategorie' => 'content_categories',
    'ContentItem' => 'content_items',
    'Domein' => 'domains',
    'Download' => 'downloads',
    'DownloadCategorie' => 'download_categories',
    'Evenement' => 'events',
    'EvenementCategorie' => 'event_categories',
    'Faq' => 'faq_items',
    'FaqCategorie' => 'faq_categories',
    'Form' => 'forms',
    'FormCategorie' => 'form_categories',
    'Isoland' => 'countries',
    'Module' => 'module_manager',
    'ModuleCategorie' => 'module_categories',
    'Order' => 'orders',
    'OrderAfleverData' => 'order_delivery_dates',
    'Redirect' => 'redirects',
    'Review' => 'catalog_reviews',
    'Role' => 'roles',
    'Slider' => 'sliders',
    'SliderCategorie' => 'slider_categories',
    'Url' => 'urls',
    'Urlverwijzing' => 'url_references',
    'User' => 'users',
    'UserCategorie' => 'user_categories',
    'Vacature' => 'vacancies',
    'VacatureCategorie' => 'vacancy_categories',
    'Vestiging' => 'locations',
    'VestigingCategorie' => 'location_categories',
];

return [
    'groups' => $groups,
    'modules' => $modules,
    'screens' => $screens,
    'root_pages' => $rootPages,
    'legacy_classes' => $legacyClasses,
];
