<?php

$groups = [
    'content' => 'Content',
    'commerce' => 'Commerce',
    'media' => 'Media',
    'users' => 'Users',
    'locations' => 'Locations',
    'events' => 'Events',
    'seo' => 'SEO',
    'modules' => 'Modules',
    'configuration' => 'Configuration',
    'localization' => 'Localization',
    'language' => 'Languages',
    'platform' => 'Platform',
];

$modules = [
    'content' => [
        'name' => 'Pages',
        'legacy_path' => 'cms/content',
        'group' => 'content',
        'table' => 'content_items',
        'title_column' => 'title',
        'description' => 'Pages, page categories, blocks, images, and attachments.',
        'legacy_tables' => ['contentitems', 'contentcategorieen', 'contentitemblock', 'contentitemafbeeldingen', 'contentitemattachment'],
    ],
    'banners' => [
        'name' => 'Banners',
        'legacy_path' => 'cms/banner',
        'group' => 'media',
        'table' => 'banners',
        'title_column' => 'title',
        'description' => 'Banner images, categories, and translations.',
        'legacy_tables' => ['banner', 'bannercategorie', 'bannerbannercategorie', 'bannertranslation'],
    ],
    'forms' => [
        'name' => 'Forms',
        'legacy_path' => 'cms/form',
        'group' => 'content',
        'table' => 'forms',
        'title_column' => 'name',
        'description' => 'Form builder blocks, rows, fields, options, messages, and submissions.',
        'legacy_tables' => ['form', 'formcategorie', 'formfield', 'formmessage', 'formulier'],
    ],
    'events' => [
        'name' => 'Events',
        'legacy_path' => 'cms/evenementen',
        'group' => 'events',
        'table' => 'events',
        'title_column' => 'title',
        'description' => 'Events, event categories, parts, images, and attachments.',
        'legacy_tables' => ['evenement', 'evenementcategorieen', 'evenementonderdeel', 'evenementafbeeldingen', 'evenementattachment'],
    ],
    'faq' => [
        'name' => 'FAQ',
        'legacy_path' => 'cms/faq',
        'group' => 'content',
        'table' => 'faq_items',
        'title_column' => 'question',
        'description' => 'Frequently asked questions and categories.',
        'legacy_tables' => ['faq', 'faqcategorie'],
    ],
    'downloads' => [
        'name' => 'Downloads',
        'legacy_path' => 'cms/download',
        'group' => 'modules',
        'table' => 'downloads',
        'title_column' => 'name',
        'description' => 'Download files and download categories.',
        'legacy_tables' => ['downloads', 'downloadcategorieen', 'downloaddownloadcategorie'],
    ],
    'locations' => [
        'name' => 'Locations',
        'legacy_path' => 'cms/vestigingen',
        'group' => 'locations',
        'table' => 'locations',
        'title_column' => 'name',
        'description' => 'Locations, categories, images, opening hours, and special opening hours.',
        'legacy_tables' => ['vestiging', 'vestigingcategorie', 'vestigingopeningstijd', 'vestigingspecialeopeningstijd'],
    ],
    'vacancies' => [
        'name' => 'Vacancies',
        'legacy_path' => 'cms/vacatures',
        'group' => 'content',
        'table' => 'vacancies',
        'title_column' => 'title',
        'description' => 'Vacancies, vacancy categories, and attachments.',
        'legacy_tables' => ['vacatures', 'vacaturecategorieen', 'vacatureattachment'],
    ],
    'catalog' => [
        'name' => 'Catalog',
        'legacy_path' => 'cms/catalogus',
        'group' => 'commerce',
        'table' => 'catalog_products',
        'title_column' => 'name',
        'description' => 'Products, categories, brands, media, translations, videos, product options, and combination sets.',
        'legacy_tables' => ['catalogusartikel', 'cataloguscategorie', 'catalogusmerk'],
    ],
    'seo' => [
        'name' => 'SEO',
        'legacy_path' => 'cms/redirect',
        'group' => 'seo',
        'table' => 'redirects',
        'title_column' => 'source_path',
        'description' => 'Redirects, URL registry, and URL references.',
        'legacy_tables' => ['redirect', 'url', 'urlverwijzing'],
    ],
    'users' => [
        'name' => 'Users',
        'legacy_path' => 'cms/users',
        'group' => 'users',
        'table' => 'users',
        'title_column' => 'name',
        'description' => 'Users, user categories, sessions, login tracking, cookies, and reset tokens.',
        'legacy_tables' => ['users', 'usercategorieen', 'userlogins', 'usersession', 'resetpassword', 'token'],
    ],
    'roles' => [
        'name' => 'Roles and Permissions',
        'legacy_path' => 'cms/roles',
        'group' => 'configuration',
        'table' => 'roles',
        'title_column' => 'name',
        'description' => 'Laravel-managed roles with permissions per module, field, and module block.',
        'legacy_tables' => ['role', 'permissions', 'rechten', 'rechtencategoriespecificatie'],
    ],
    'countries' => [
        'name' => 'Countries',
        'legacy_path' => 'cms/landen',
        'group' => 'configuration',
        'table' => 'countries',
        'title_column' => 'name',
        'description' => 'Package-backed countries, website languages, and ISO language data.',
        'legacy_tables' => ['countries', 'country_codes', 'languages', 'iso_languages'],
    ],
    'translations' => [
        'name' => 'Translations',
        'legacy_path' => 'cms/translations',
        'group' => 'localization',
        'table' => 'translation_keys',
        'title_column' => 'key',
        'description' => 'Translation keys, values, source strings, and runtime translations.',
        'legacy_tables' => ['translatekey', 'translatecontent', 'translation'],
    ],
    'navigation' => [
        'name' => 'Navigation',
        'legacy_path' => 'cms/navigation',
        'group' => 'website',
        'table' => 'navigation_menus',
        'title_column' => 'name',
        'description' => 'Reusable website navigation menus with module links and drag-and-drop nesting.',
        'legacy_tables' => [],
    ],
];

$screens = [
    'content_items' => [
        'name' => 'Pages',
        'legacy_path' => 'cms/content',
        'group' => 'content',
        'table' => 'content_items',
        'title_column' => 'title',
        'description' => 'Legacy page overview and editor.',
        'legacy_tables' => ['contentitems'],
        'pages' => [
            'index' => ['name' => 'Pages overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit page', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Page images', 'type' => 'edit', 'table' => 'content_images', 'title_column' => 'caption', 'legacy_tables' => ['contentitemafbeeldingen']],
        ],
    ],
    'content_categories' => [
        'name' => 'Page Categories',
        'parent_screen' => 'content_items',
        'legacy_path' => 'cms/content/categorieen',
        'group' => 'content',
        'table' => 'content_categories',
        'title_column' => 'name',
        'description' => 'Legacy page category tree and editor.',
        'legacy_tables' => ['contentcategorieen', 'contentcategorieafbeeldingen'],
        'pages' => [
            'index' => ['name' => 'Page category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit page category', 'type' => 'edit'],
        ],
    ],
    'events' => [
        'name' => 'Events',
        'legacy_path' => 'cms/evenementen',
        'group' => 'events',
        'table' => 'events',
        'title_column' => 'title',
        'description' => 'Legacy events overview and editor.',
        'legacy_tables' => ['evenement'],
        'pages' => [
            'index' => ['name' => 'Events overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit event', 'type' => 'edit'],
        ],
    ],
    'event_categories' => [
        'name' => 'Event Categories',
        'parent_screen' => 'events',
        'legacy_path' => 'cms/evenementen/categorieen',
        'group' => 'events',
        'table' => 'event_categories',
        'title_column' => 'name',
        'description' => 'Legacy event category overview and editor.',
        'legacy_tables' => ['evenementcategorieen'],
        'pages' => [
            'index' => ['name' => 'Event category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit event category', 'type' => 'edit'],
        ],
    ],
    'faq_items' => [
        'name' => 'FAQ',
        'legacy_path' => 'cms/faq',
        'group' => 'content',
        'table' => 'faq_items',
        'title_column' => 'question',
        'description' => 'Legacy FAQ overview and editor.',
        'legacy_tables' => ['faq'],
        'pages' => [
            'index' => ['name' => 'FAQ overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit FAQ item', 'type' => 'edit'],
        ],
    ],
    'faq_categories' => [
        'name' => 'FAQ Categories',
        'parent_screen' => 'faq_items',
        'legacy_path' => 'cms/faq/categorieen',
        'group' => 'content',
        'table' => 'faq_categories',
        'title_column' => 'name',
        'description' => 'Legacy FAQ category overview and editor.',
        'legacy_tables' => ['faqcategorie'],
        'pages' => [
            'index' => ['name' => 'FAQ category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit FAQ category', 'type' => 'edit'],
        ],
    ],
    'forms' => [
        'name' => 'Forms',
        'legacy_path' => 'cms/form',
        'group' => 'content',
        'table' => 'forms',
        'title_column' => 'name',
        'description' => 'Legacy form builder overview and editor.',
        'legacy_tables' => ['form'],
        'pages' => [
            'index' => ['name' => 'Forms overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit form', 'type' => 'edit'],
            'editMessages' => ['name' => 'Form messages', 'type' => 'edit', 'table' => 'form_messages', 'title_column' => 'subject', 'legacy_tables' => ['formmessage']],
        ],
    ],
    'form_categories' => [
        'name' => 'Form Categories',
        'parent_screen' => 'forms',
        'legacy_path' => 'cms/form/categorieen',
        'group' => 'content',
        'table' => 'form_categories',
        'title_column' => 'name',
        'description' => 'Legacy form category overview and editor.',
        'legacy_tables' => ['formcategorie'],
        'pages' => [
            'index' => ['name' => 'Form category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit form category', 'type' => 'edit'],
        ],
    ],
    'vacancies' => [
        'name' => 'Vacancies',
        'legacy_path' => 'cms/vacatures',
        'group' => 'content',
        'table' => 'vacancies',
        'title_column' => 'title',
        'admin_route' => 'admin.vacancies.index',
        'description' => 'Legacy vacancy overview and editor.',
        'legacy_tables' => ['vacatures'],
        'pages' => [
            'index' => ['name' => 'Vacancy overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit vacancy', 'type' => 'edit'],
            'seo' => ['name' => 'SEO settings', 'type' => 'edit'],
        ],
    ],
    'vacancy_categories' => [
        'name' => 'Vacancy Categories',
        'parent_screen' => 'vacancies',
        'legacy_path' => 'cms/vacatures/categorieen',
        'group' => 'content',
        'table' => 'vacancy_categories',
        'title_column' => 'name',
        'admin_route' => 'admin.vacancies.categories.index',
        'description' => 'Legacy vacancy category overview and editor.',
        'legacy_tables' => ['vacaturecategorieen'],
        'pages' => [
            'index' => ['name' => 'Vacancy category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit vacancy category', 'type' => 'edit'],
        ],
    ],
    'banners' => [
        'name' => 'Banners',
        'legacy_path' => 'cms/banner',
        'group' => 'media',
        'table' => 'banners',
        'title_column' => 'title',
        'description' => 'Legacy banner overview, editor, and bulk upload screen.',
        'legacy_tables' => ['banner'],
        'pages' => [
            'index' => ['name' => 'Banners overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit banner', 'type' => 'edit'],
            'bulkUploader' => ['name' => 'Bulk banner uploader', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'banner_categories' => [
        'name' => 'Banner Categories',
        'parent_screen' => 'banners',
        'legacy_path' => 'cms/banner/categorieen',
        'group' => 'media',
        'table' => 'banner_categories',
        'title_column' => 'name',
        'description' => 'Legacy banner category overview and editor.',
        'legacy_tables' => ['bannercategorie'],
        'pages' => [
            'index' => ['name' => 'Banner category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit banner category', 'type' => 'edit'],
        ],
    ],
    'catalog_products' => [
        'name' => 'Catalog Products',
        'legacy_path' => 'cms/catalogus',
        'group' => 'commerce',
        'table' => 'catalog_products',
        'title_column' => 'name',
        'description' => 'Legacy catalog product overview and editor.',
        'legacy_tables' => ['catalogusartikel'],
        'pages' => [
            'index' => ['name' => 'Catalog product overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog product', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Product images', 'type' => 'edit', 'table' => 'catalog_product_images', 'title_column' => 'caption', 'legacy_tables' => ['catalogusartikelafbeelding']],
            'editOptions' => ['name' => 'Product options', 'type' => 'edit', 'table' => 'catalog_product_options', 'title_column' => 'label', 'legacy_tables' => ['catalogusartikeloption']],
            'editVertalingen' => ['name' => 'Product translations', 'type' => 'edit', 'table' => 'catalog_product_translations', 'title_column' => 'title', 'legacy_tables' => ['catalogusvertaling']],
            'editVideo' => ['name' => 'Product videos', 'type' => 'edit', 'table' => 'catalog_product_videos', 'title_column' => 'title', 'legacy_tables' => ['catalogusvideo']],
            'resetSortIndex' => ['name' => 'Reset product sort order', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'catalog_combination_sets' => [
        'name' => 'Catalog Combination Sets',
        'parent_screen' => 'catalog_products',
        'legacy_path' => 'cms/catalogus/combinaties',
        'group' => 'commerce',
        'table' => 'catalog_combination_sets',
        'title_column' => 'name',
        'description' => 'Reusable catalog product combination sets.',
        'legacy_tables' => ['cataloguscombinatie'],
        'pages' => [
            'index' => ['name' => 'Catalog combination set overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog combination set', 'type' => 'edit'],
        ],
    ],
    'catalog_categories' => [
        'name' => 'Catalog Categories',
        'parent_screen' => 'catalog_products',
        'legacy_path' => 'cms/catalogus/categorieen',
        'group' => 'commerce',
        'table' => 'catalog_categories',
        'title_column' => 'name',
        'description' => 'Legacy catalog category overview and editor.',
        'legacy_tables' => ['cataloguscategorie'],
        'pages' => [
            'index' => ['name' => 'Catalog category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog category', 'type' => 'edit'],
        ],
    ],
    'catalog_brands' => [
        'name' => 'Catalog Brands',
        'legacy_path' => 'cms/catalogus/merken',
        'group' => 'commerce',
        'table' => 'catalog_brands',
        'title_column' => 'name',
        'description' => 'Legacy catalog brand overview and editor.',
        'legacy_tables' => ['catalogusmerk'],
        'pages' => [
            'index' => ['name' => 'Catalog brand overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog brand', 'type' => 'edit'],
        ],
    ],
    'users' => [
        'name' => 'Users',
        'legacy_path' => 'cms/users',
        'group' => 'users',
        'table' => 'users',
        'title_column' => 'name',
        'description' => 'Laravel users enhanced with legacy CMS profile fields, categories, active windows, and roles.',
        'legacy_tables' => ['users'],
        'pages' => [
            'index' => ['name' => 'User overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit user', 'type' => 'edit'],
            'resetPassword' => ['name' => 'Reset user password', 'type' => 'utility', 'read_only' => true],
            'wachtwoordvergeten' => ['name' => 'Forgotten password', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'user_categories' => [
        'name' => 'User Categories',
        'parent_screen' => 'users',
        'legacy_path' => 'cms/users/categorieen',
        'group' => 'users',
        'table' => 'user_categories',
        'title_column' => 'name',
        'description' => 'Legacy user category overview and editor.',
        'legacy_tables' => ['usercategorieen'],
        'pages' => [
            'index' => ['name' => 'User category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit user category', 'type' => 'edit'],
        ],
    ],
    'locations' => [
        'name' => 'Locations',
        'legacy_path' => 'cms/vestigingen',
        'group' => 'locations',
        'table' => 'locations',
        'title_column' => 'name',
        'description' => 'Legacy location overview and editor.',
        'legacy_tables' => ['vestiging'],
        'pages' => [
            'index' => ['name' => 'Location overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit location', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Location images', 'type' => 'edit', 'table' => 'location_images', 'title_column' => 'caption', 'legacy_tables' => ['vestigingafbeeldingen']],
            'editOpeningstijden' => ['name' => 'Location opening hours', 'type' => 'edit', 'table' => 'location_opening_hours', 'title_column' => 'day', 'legacy_tables' => ['vestigingopeningstijd', 'vestigingspecialeopeningstijd']],
        ],
    ],
    'location_categories' => [
        'name' => 'Location Categories',
        'parent_screen' => 'locations',
        'legacy_path' => 'cms/vestigingen/categorieen',
        'group' => 'locations',
        'table' => 'location_categories',
        'title_column' => 'name',
        'description' => 'Legacy location category overview and editor.',
        'legacy_tables' => ['vestigingcategorie'],
        'pages' => [
            'index' => ['name' => 'Location category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit location category', 'type' => 'edit'],
        ],
    ],
    'navigation' => [
        'name' => 'Navigation',
        'legacy_path' => 'cms/navigation',
        'group' => 'website',
        'table' => 'navigation_menus',
        'title_column' => 'name',
        'admin_route' => 'admin.navigation.index',
        'description' => 'Website navigation builder with custom URLs, module targets, active states, and nested menus.',
        'legacy_tables' => [],
        'pages' => [
            'index' => ['name' => 'Navigation overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit navigation menu', 'type' => 'edit'],
        ],
    ],
    'redirects' => [
        'name' => 'Redirects',
        'legacy_path' => 'cms/redirect',
        'group' => 'seo',
        'table' => 'redirects',
        'title_column' => 'source_path',
        'description' => 'Legacy redirect overview and editor.',
        'legacy_tables' => ['redirect'],
        'pages' => [
            'index' => ['name' => 'Redirect overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit redirect', 'type' => 'edit'],
        ],
    ],
    'urls' => [
        'name' => 'URLs',
        'legacy_path' => 'cms/url',
        'group' => 'seo',
        'table' => 'urls',
        'title_column' => 'path',
        'description' => 'Legacy URL registry overview and editor.',
        'legacy_tables' => ['url'],
        'pages' => [
            'index' => ['name' => 'URL overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit URL', 'type' => 'edit'],
        ],
    ],
    'url_references' => [
        'name' => 'URL References',
        'legacy_path' => 'cms/urlverwijzingen',
        'group' => 'seo',
        'table' => 'url_references',
        'title_column' => 'source_path',
        'description' => 'Legacy URL reference overview and editor.',
        'legacy_tables' => ['urlverwijzing'],
        'pages' => [
            'index' => ['name' => 'URL reference overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit URL reference', 'type' => 'edit'],
        ],
    ],
    'downloads' => [
        'name' => 'Downloads',
        'legacy_path' => 'cms/download',
        'group' => 'modules',
        'table' => 'downloads',
        'title_column' => 'name',
        'description' => 'Legacy download overview and editor.',
        'legacy_tables' => ['downloads'],
        'pages' => [
            'index' => ['name' => 'Download overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit download', 'type' => 'edit'],
        ],
    ],
    'download_categories' => [
        'name' => 'Download Categories',
        'parent_screen' => 'downloads',
        'legacy_path' => 'cms/download/categorieen',
        'group' => 'modules',
        'table' => 'download_categories',
        'title_column' => 'name',
        'description' => 'Legacy download category overview and editor.',
        'legacy_tables' => ['downloadcategorieen'],
        'pages' => [
            'index' => ['name' => 'Download category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit download category', 'type' => 'edit'],
        ],
    ],
    'roles' => [
        'name' => 'Roles and Permissions',
        'legacy_path' => 'cms/roles',
        'group' => 'configuration',
        'table' => 'roles',
        'title_column' => 'name',
        'description' => 'Laravel role and permission overview with module, field, and block permissions.',
        'legacy_tables' => ['role', 'rechten'],
        'pages' => [
            'index' => ['name' => 'Role overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit role', 'type' => 'edit'],
        ],
    ],
    'domains' => [
        'name' => 'Domains',
        'legacy_path' => 'cms/domein',
        'group' => 'configuration',
        'table' => 'domains',
        'title_column' => 'host',
        'admin_route' => 'admin.domains.index',
        'description' => 'Legacy domain overview and editor.',
        'legacy_tables' => ['domein'],
        'pages' => [
            'index' => ['name' => 'Domain overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit domain', 'type' => 'edit'],
        ],
    ],
    'website_templates' => [
        'name' => 'Website Templates',
        'legacy_path' => 'cms/templates',
        'group' => 'configuration',
        'table' => 'website_templates',
        'title_column' => 'name',
        'admin_route' => 'admin.templates.index',
        'description' => 'Reusable vanilla Sass website templates and their default domain settings.',
        'legacy_tables' => [],
        'pages' => [
            'index' => ['name' => 'Template overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit template', 'type' => 'edit'],
        ],
    ],
    'base_module_conventions' => [
        'name' => 'Base Module Conventions',
        'legacy_path' => 'cms/base-module-conventions',
        'group' => 'platform',
        'table' => null,
        'title_column' => 'title',
        'admin_route' => 'admin.base-module-conventions.index',
        'description' => 'Reference admin layout sets for new reusable base modules.',
        'legacy_tables' => [],
        'pages' => [
            'index' => ['name' => 'Base module conventions', 'type' => 'index'],
        ],
    ],
    'countries' => [
        'name' => 'Countries',
        'legacy_path' => 'cms/landen',
        'group' => 'configuration',
        'table' => 'countries',
        'title_column' => 'name',
        'description' => 'Package-backed country overview, country editor, and website language settings.',
        'legacy_tables' => ['countries', 'iso_languages', 'languages'],
        'pages' => [
            'index' => ['name' => 'Country overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit country', 'type' => 'edit'],
            'talen' => ['name' => 'Website languages', 'type' => 'index'],
        ],
    ],
    'translations' => [
        'name' => 'Translations',
        'legacy_path' => 'cms/translations',
        'group' => 'localization',
        'table' => 'translation_keys',
        'title_column' => 'key',
        'description' => 'Backend and frontend translation key overview and editor.',
        'legacy_tables' => ['translatekey', 'translatecontent', 'translation'],
        'pages' => [
            'index' => ['name' => 'Translation overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit translation', 'type' => 'edit'],
            'sync' => ['name' => 'Synchronize translations', 'type' => 'utility'],
        ],
    ],
];

$rootPages = [
    'dashboard' => ['name' => 'Dashboard', 'type' => 'dashboard'],
    'firstLogin' => ['name' => 'First login', 'type' => 'utility'],
    'resetpass' => ['name' => 'Reset password', 'type' => 'utility'],
    'token' => ['name' => 'Token login', 'type' => 'utility'],
    'delete' => ['name' => 'Delete record', 'type' => 'utility'],
];

$legacyClasses = [
    'Banner' => 'banners',
    'BannerCategorie' => 'banner_categories',
    'CatalogusArtikel' => 'catalog_products',
    'CatalogusCategorie' => 'catalog_categories',
    'CatalogusMerk' => 'catalog_brands',
    'ContentCategorie' => 'content_categories',
    'ContentItem' => 'content_items',
    'Domein' => 'domains',
    'Download' => 'downloads',
    'DownloadCategorie' => 'download_categories',
    'Evenement' => 'events',
    'EvenementCategorie' => 'event_categories',
    'Faq' => 'faq_items',
    'FaqCategorie' => 'faq_categories',
    'Form' => 'forms',
    'FormCategorie' => 'form_categories',
    'Country' => 'countries',
    'Redirect' => 'redirects',
    'Role' => 'roles',
    'Url' => 'urls',
    'Urlverwijzing' => 'url_references',
    'User' => 'users',
    'UserCategorie' => 'user_categories',
    'Vacature' => 'vacancies',
    'VacatureCategorie' => 'vacancy_categories',
    'Vestiging' => 'locations',
    'VestigingCategorie' => 'location_categories',
];

return [
    'groups' => $groups,
    'modules' => $modules,
    'screens' => $screens,
    'root_pages' => $rootPages,
    'legacy_classes' => $legacyClasses,
];
