<?php

$groups = [
    'content' => 'Content',
    'media' => 'Media',
    'commerce' => 'Commerce',
    'users' => 'Users',
    'locations' => 'Locations',
    'seo' => 'SEO',
    'modules' => 'Modules',
    'configuration' => 'Configuration',
    'communication' => 'Communication',
    'localization' => 'Localization',
    'platform' => 'Platform',
    'website' => 'Website',
];

$modules = [
    'content' => [
        'name' => 'Content',
        'legacy_path' => 'wms/content',
        'group' => 'content',
        'table' => 'wms_content_items',
        'title_column' => 'title',
        'description' => 'Pages, content categories, blocks, images, and attachments.',
        'legacy_tables' => ['contentitems', 'contentcategorieen', 'contentitemblock', 'contentitemafbeeldingen', 'contentitemattachment'],
    ],
    'banners' => [
        'name' => 'Banners',
        'legacy_path' => 'wms/banner',
        'group' => 'media',
        'table' => 'wms_banners',
        'title_column' => 'title',
        'description' => 'Banner images, categories, and translations.',
        'legacy_tables' => ['banner', 'bannercategorie', 'bannerbannercategorie', 'bannertranslation'],
    ],
    'sliders' => [
        'name' => 'Sliders',
        'legacy_path' => 'wms/slider',
        'group' => 'media',
        'table' => 'wms_sliders',
        'title_column' => 'title',
        'description' => 'Slider images, categories, links, and display windows.',
        'legacy_tables' => ['slider', 'slidercategorie', 'sliderslidercategorie'],
    ],
    'forms' => [
        'name' => 'Forms',
        'legacy_path' => 'wms/form',
        'group' => 'content',
        'table' => 'wms_forms',
        'title_column' => 'name',
        'description' => 'Form builder blocks, rows, fields, options, messages, and submissions.',
        'legacy_tables' => ['form', 'formcategorie', 'formfield', 'formmessage', 'formulier'],
    ],
    'events' => [
        'name' => 'Events',
        'legacy_path' => 'wms/evenementen',
        'group' => 'content',
        'table' => 'wms_events',
        'title_column' => 'title',
        'description' => 'Events, event categories, parts, images, and attachments.',
        'legacy_tables' => ['evenement', 'evenementcategorieen', 'evenementonderdeel', 'evenementafbeeldingen', 'evenementattachment'],
    ],
    'faq' => [
        'name' => 'FAQ',
        'legacy_path' => 'wms/faq',
        'group' => 'content',
        'table' => 'wms_faq_items',
        'title_column' => 'question',
        'description' => 'Frequently asked questions, categories, images, videos, and attachments.',
        'legacy_tables' => ['faq', 'faqcategorie', 'faqafbeeldingen', 'faqattachment', 'faqvideo'],
    ],
    'downloads' => [
        'name' => 'Downloads',
        'legacy_path' => 'wms/download',
        'group' => 'modules',
        'table' => 'wms_downloads',
        'title_column' => 'name',
        'description' => 'Download files and download categories.',
        'legacy_tables' => ['downloads', 'downloadcategorieen', 'downloaddownloadcategorie'],
    ],
    'locations' => [
        'name' => 'Locations',
        'legacy_path' => 'wms/vestigingen',
        'group' => 'locations',
        'table' => 'wms_locations',
        'title_column' => 'name',
        'description' => 'Locations, categories, images, opening hours, and special opening hours.',
        'legacy_tables' => ['vestiging', 'vestigingcategorie', 'vestigingopeningstijd', 'vestigingspecialeopeningstijd'],
    ],
    'vacancies' => [
        'name' => 'Vacancies',
        'legacy_path' => 'wms/vacatures',
        'group' => 'content',
        'table' => 'wms_vacancies',
        'title_column' => 'title',
        'description' => 'Vacancies, vacancy categories, and attachments.',
        'legacy_tables' => ['vacatures', 'vacaturecategorieen', 'vacatureattachment'],
    ],
    'catalog' => [
        'name' => 'Catalog',
        'legacy_path' => 'wms/catalogus',
        'group' => 'commerce',
        'table' => 'wms_catalog_products',
        'title_column' => 'name',
        'description' => 'Products, categories, brands, promotions, discounts, media, stock, reviews, and product options.',
        'legacy_tables' => ['catalogusartikel', 'cataloguscategorie', 'catalogusmerk', 'cataloguspromotie', 'catalogusreview', 'actiecode'],
    ],
    'orders' => [
        'name' => 'Orders',
        'legacy_path' => 'wms/orders',
        'group' => 'commerce',
        'table' => 'wms_orders',
        'title_column' => 'order_number',
        'description' => 'Orders, order lines, delivery dates, and delivery settings.',
        'legacy_tables' => ['orders', 'orderregels', 'orderafleverdata', 'orderafleverdatadag', 'orderafleverdatadatum'],
    ],
    'mailing_contacts' => [
        'name' => 'Mailing Contacts',
        'legacy_path' => 'wms/mailingcontacten',
        'group' => 'communication',
        'table' => 'wms_mailing_contacts',
        'title_column' => 'email',
        'description' => 'Mailing contacts, contact categories, import, export, groups, blacklists, tokens, and opens.',
        'legacy_tables' => ['mailingcontacten', 'mailingcontactcategorieen', 'mailinggroep', 'mailinggeopend'],
    ],
    'radio' => [
        'name' => 'Radio',
        'legacy_path' => 'wms/radio',
        'group' => 'media',
        'table' => 'wms_radio_programs',
        'title_column' => 'title',
        'description' => 'Radio guides, programs, and schedule entries.',
        'legacy_tables' => ['radiogids', 'radioprogramma', 'radioschedule'],
    ],
    'seo' => [
        'name' => 'SEO',
        'legacy_path' => 'wms/redirect',
        'group' => 'seo',
        'table' => 'wms_redirects',
        'title_column' => 'source_path',
        'description' => 'Redirects, URL registry, URL references, and stored search keywords.',
        'legacy_tables' => ['redirect', 'url', 'urlverwijzing', 'zoekwoorden'],
    ],
    'users' => [
        'name' => 'Users',
        'legacy_path' => 'wms/users',
        'group' => 'users',
        'table' => 'users',
        'title_column' => 'name',
        'read_only' => true,
        'description' => 'Users, user categories, sessions, login tracking, cookies, and reset tokens.',
        'legacy_tables' => ['users', 'usercategorieen', 'userlogins', 'usersession', 'resetpassword', 'token'],
    ],
    'roles' => [
        'name' => 'Roles and Permissions',
        'legacy_path' => 'wms/rbac',
        'group' => 'configuration',
        'table' => 'wms_roles',
        'title_column' => 'name',
        'description' => 'Roles, permissions, rights, category-specific rights, page permissions, and RBAC logs.',
        'legacy_tables' => ['role', 'permissions', 'rechten', 'rechtencategoriespecificatie', 'rbaclog'],
    ],
    'module_manager' => [
        'name' => 'Module Manager',
        'legacy_path' => 'wms/module',
        'group' => 'configuration',
        'table' => 'cms_modules',
        'title_column' => 'name',
        'read_only' => true,
        'description' => 'Base and website module registration, categories, and sort order.',
        'legacy_tables' => ['module', 'modulecategorie', 'modulemodulecategorie'],
    ],
    'countries' => [
        'name' => 'Countries',
        'legacy_path' => 'wms/isolanden',
        'group' => 'configuration',
        'table' => 'wms_countries',
        'title_column' => 'name',
        'description' => 'Countries, country codes, ISO languages, and payment-country settings.',
        'legacy_tables' => ['isolanden', 'isolandcode', 'isolandbetalingswijze', 'landen', 'isotalen', 'talen'],
    ],
    'translations' => [
        'name' => 'Translations',
        'legacy_path' => 'wms/translations',
        'group' => 'localization',
        'table' => 'wms_translation_keys',
        'title_column' => 'key',
        'description' => 'Translation keys, values, source strings, and runtime translations.',
        'legacy_tables' => ['translatekey', 'translatecontent', 'translation'],
    ],
    'search_keywords' => [
        'name' => 'Search Keywords',
        'legacy_path' => 'wms/zoekwoorden',
        'group' => 'seo',
        'table' => 'wms_search_keywords',
        'title_column' => 'keyword',
        'description' => 'Stored website search keywords and request metadata.',
        'legacy_tables' => ['zoekwoorden'],
    ],
    'guestbook' => [
        'name' => 'Guestbook',
        'legacy_path' => 'wms/gastenboek',
        'group' => 'website',
        'table' => 'wms_guestbook_entries',
        'title_column' => 'author_name',
        'description' => 'Guestbook messages and publication status.',
        'legacy_tables' => ['gastenboek'],
    ],
];

$screens = [
    'content_items' => [
        'name' => 'Content',
        'legacy_path' => 'wms/content',
        'group' => 'content',
        'table' => 'wms_content_items',
        'title_column' => 'title',
        'description' => 'Legacy content item overview and editor.',
        'legacy_tables' => ['contentitems'],
        'pages' => [
            'index' => ['name' => 'Content overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit content item', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Content images', 'type' => 'edit', 'table' => 'wms_content_images', 'title_column' => 'caption', 'legacy_tables' => ['contentitemafbeeldingen']],
            'editSlider' => ['name' => 'Content slider', 'type' => 'edit', 'table' => 'wms_sliders', 'title_column' => 'title', 'legacy_tables' => ['slider']],
        ],
    ],
    'content_categories' => [
        'name' => 'Content Categories',
        'legacy_path' => 'wms/content/categorieen',
        'group' => 'content',
        'table' => 'wms_content_categories',
        'title_column' => 'name',
        'description' => 'Legacy content category tree and editor.',
        'legacy_tables' => ['contentcategorieen', 'contentcategorieafbeeldingen'],
        'pages' => [
            'index' => ['name' => 'Category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit content category', 'type' => 'edit'],
            'editSlider' => ['name' => 'Category slider', 'type' => 'edit', 'table' => 'wms_sliders', 'title_column' => 'title', 'legacy_tables' => ['slider']],
        ],
    ],
    'events' => [
        'name' => 'Events',
        'legacy_path' => 'wms/evenementen',
        'group' => 'content',
        'table' => 'wms_events',
        'title_column' => 'title',
        'description' => 'Legacy events overview and editor.',
        'legacy_tables' => ['evenement'],
        'pages' => [
            'index' => ['name' => 'Events overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit event', 'type' => 'edit'],
        ],
    ],
    'event_categories' => [
        'name' => 'Event Categories',
        'legacy_path' => 'wms/evenementen/categorieen',
        'group' => 'content',
        'table' => 'wms_event_categories',
        'title_column' => 'name',
        'description' => 'Legacy event category overview and editor.',
        'legacy_tables' => ['evenementcategorieen'],
        'pages' => [
            'index' => ['name' => 'Event category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit event category', 'type' => 'edit'],
        ],
    ],
    'faq_items' => [
        'name' => 'FAQ',
        'legacy_path' => 'wms/faq',
        'group' => 'content',
        'table' => 'wms_faq_items',
        'title_column' => 'question',
        'description' => 'Legacy FAQ overview and editor.',
        'legacy_tables' => ['faq'],
        'pages' => [
            'index' => ['name' => 'FAQ overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit FAQ item', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'FAQ images', 'type' => 'edit', 'table' => 'wms_faq_images', 'title_column' => 'caption', 'legacy_tables' => ['faqafbeeldingen']],
            'editVideo' => ['name' => 'FAQ videos', 'type' => 'edit', 'table' => 'wms_faq_videos', 'title_column' => 'title', 'legacy_tables' => ['faqvideo']],
        ],
    ],
    'faq_categories' => [
        'name' => 'FAQ Categories',
        'legacy_path' => 'wms/faq/categorieen',
        'group' => 'content',
        'table' => 'wms_faq_categories',
        'title_column' => 'name',
        'description' => 'Legacy FAQ category overview and editor.',
        'legacy_tables' => ['faqcategorie'],
        'pages' => [
            'index' => ['name' => 'FAQ category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit FAQ category', 'type' => 'edit'],
        ],
    ],
    'forms' => [
        'name' => 'Forms',
        'legacy_path' => 'wms/form',
        'group' => 'content',
        'table' => 'wms_forms',
        'title_column' => 'name',
        'description' => 'Legacy form builder overview and editor.',
        'legacy_tables' => ['form'],
        'pages' => [
            'index' => ['name' => 'Forms overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit form', 'type' => 'edit'],
            'editMessages' => ['name' => 'Form messages', 'type' => 'edit', 'table' => 'wms_form_messages', 'title_column' => 'subject', 'legacy_tables' => ['formmessage']],
        ],
    ],
    'form_categories' => [
        'name' => 'Form Categories',
        'legacy_path' => 'wms/form/categorieen',
        'group' => 'content',
        'table' => 'wms_form_categories',
        'title_column' => 'name',
        'description' => 'Legacy form category overview and editor.',
        'legacy_tables' => ['formcategorie'],
        'pages' => [
            'index' => ['name' => 'Form category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit form category', 'type' => 'edit'],
        ],
    ],
    'vacancies' => [
        'name' => 'Vacancies',
        'legacy_path' => 'wms/vacatures',
        'group' => 'content',
        'table' => 'wms_vacancies',
        'title_column' => 'title',
        'description' => 'Legacy vacancy overview and editor.',
        'legacy_tables' => ['vacatures'],
        'pages' => [
            'index' => ['name' => 'Vacancy overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit vacancy', 'type' => 'edit'],
        ],
    ],
    'vacancy_categories' => [
        'name' => 'Vacancy Categories',
        'legacy_path' => 'wms/vacatures/categorieen',
        'group' => 'content',
        'table' => 'wms_vacancy_categories',
        'title_column' => 'name',
        'description' => 'Legacy vacancy category overview and editor.',
        'legacy_tables' => ['vacaturecategorieen'],
        'pages' => [
            'index' => ['name' => 'Vacancy category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit vacancy category', 'type' => 'edit'],
        ],
    ],
    'banners' => [
        'name' => 'Banners',
        'legacy_path' => 'wms/banner',
        'group' => 'media',
        'table' => 'wms_banners',
        'title_column' => 'title',
        'description' => 'Legacy banner overview, editor, and bulk upload screen.',
        'legacy_tables' => ['banner'],
        'pages' => [
            'index' => ['name' => 'Banners overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit banner', 'type' => 'edit'],
            'bulkUploader' => ['name' => 'Bulk banner uploader', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'banner_categories' => [
        'name' => 'Banner Categories',
        'legacy_path' => 'wms/banner/categorieen',
        'group' => 'media',
        'table' => 'wms_banner_categories',
        'title_column' => 'name',
        'description' => 'Legacy banner category overview and editor.',
        'legacy_tables' => ['bannercategorie'],
        'pages' => [
            'index' => ['name' => 'Banner category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit banner category', 'type' => 'edit'],
        ],
    ],
    'radio_guides' => [
        'name' => 'Radio Guides',
        'legacy_path' => 'wms/radio/gidsen',
        'group' => 'media',
        'table' => 'wms_radio_guides',
        'title_column' => 'name',
        'description' => 'Legacy radio guide overview, editor, and schedule screen.',
        'legacy_tables' => ['radiogids'],
        'pages' => [
            'index' => ['name' => 'Radio guide overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit radio guide', 'type' => 'edit'],
            'schedule' => ['name' => 'Radio guide schedule', 'type' => 'edit', 'table' => 'wms_radio_schedules', 'title_column' => 'day', 'legacy_tables' => ['radioschedule']],
        ],
    ],
    'radio_programs' => [
        'name' => 'Radio Programs',
        'legacy_path' => 'wms/radio/programmas',
        'group' => 'media',
        'table' => 'wms_radio_programs',
        'title_column' => 'title',
        'description' => 'Legacy radio program overview and editor.',
        'legacy_tables' => ['radioprogramma'],
        'pages' => [
            'index' => ['name' => 'Radio program overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit radio program', 'type' => 'edit'],
        ],
    ],
    'sliders' => [
        'name' => 'Sliders',
        'legacy_path' => 'wms/slider',
        'group' => 'media',
        'table' => 'wms_sliders',
        'title_column' => 'title',
        'description' => 'Legacy slider overview and editor.',
        'legacy_tables' => ['slider'],
        'pages' => [
            'index' => ['name' => 'Slider overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit slider', 'type' => 'edit'],
        ],
    ],
    'slider_categories' => [
        'name' => 'Slider Categories',
        'legacy_path' => 'wms/slider/categorieen',
        'group' => 'media',
        'table' => 'wms_slider_categories',
        'title_column' => 'name',
        'description' => 'Legacy slider category overview and editor.',
        'legacy_tables' => ['slidercategorie'],
        'pages' => [
            'index' => ['name' => 'Slider category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit slider category', 'type' => 'edit'],
        ],
    ],
    'catalog_products' => [
        'name' => 'Catalog Products',
        'legacy_path' => 'wms/catalogus',
        'group' => 'commerce',
        'table' => 'wms_catalog_products',
        'title_column' => 'name',
        'description' => 'Legacy catalog product overview and editor.',
        'legacy_tables' => ['catalogusartikel'],
        'pages' => [
            'index' => ['name' => 'Catalog product overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog product', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Product images', 'type' => 'edit', 'table' => 'wms_catalog_product_images', 'title_column' => 'caption', 'legacy_tables' => ['catalogusartikelafbeelding']],
            'editCombinaties' => ['name' => 'Product combinations', 'type' => 'edit', 'table' => 'wms_catalog_product_combinations', 'title_column' => 'catalog_product_id', 'legacy_tables' => ['cataloguscombinatie']],
            'editOptions' => ['name' => 'Product options', 'type' => 'edit', 'table' => 'wms_catalog_product_options', 'title_column' => 'label', 'legacy_tables' => ['catalogusartikeloption']],
            'editVertalingen' => ['name' => 'Product translations', 'type' => 'edit', 'table' => 'wms_catalog_product_translations', 'title_column' => 'title', 'legacy_tables' => ['catalogusvertaling']],
            'editVideo' => ['name' => 'Product videos', 'type' => 'edit', 'table' => 'wms_catalog_product_videos', 'title_column' => 'title', 'legacy_tables' => ['catalogusvideo']],
            'editVoorraad' => ['name' => 'Product stock', 'type' => 'edit', 'table' => 'wms_catalog_stock', 'title_column' => 'catalog_product_id', 'legacy_tables' => ['catalogusvoorraad']],
            'resetSortIndex' => ['name' => 'Reset product sort order', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'catalog_categories' => [
        'name' => 'Catalog Categories',
        'legacy_path' => 'wms/catalogus/categorieen',
        'group' => 'commerce',
        'table' => 'wms_catalog_categories',
        'title_column' => 'name',
        'description' => 'Legacy catalog category overview and editor.',
        'legacy_tables' => ['cataloguscategorie'],
        'pages' => [
            'index' => ['name' => 'Catalog category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog category', 'type' => 'edit'],
        ],
    ],
    'catalog_brands' => [
        'name' => 'Catalog Brands',
        'legacy_path' => 'wms/catalogus/merken',
        'group' => 'commerce',
        'table' => 'wms_catalog_brands',
        'title_column' => 'name',
        'description' => 'Legacy catalog brand overview and editor.',
        'legacy_tables' => ['catalogusmerk'],
        'pages' => [
            'index' => ['name' => 'Catalog brand overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog brand', 'type' => 'edit'],
        ],
    ],
    'catalog_promotions' => [
        'name' => 'Catalog Promotions',
        'legacy_path' => 'wms/catalogus/promotie',
        'group' => 'commerce',
        'table' => 'wms_catalog_promotions',
        'title_column' => 'name',
        'description' => 'Legacy catalog promotion overview and editor.',
        'legacy_tables' => ['cataloguspromotie'],
        'pages' => [
            'index' => ['name' => 'Catalog promotion overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog promotion', 'type' => 'edit'],
        ],
    ],
    'catalog_reviews' => [
        'name' => 'Catalog Reviews',
        'legacy_path' => 'wms/catalogus/review',
        'group' => 'commerce',
        'table' => 'wms_catalog_reviews',
        'title_column' => 'title',
        'description' => 'Legacy catalog review overview and editor.',
        'legacy_tables' => ['catalogusreview'],
        'pages' => [
            'index' => ['name' => 'Catalog review overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit catalog review', 'type' => 'edit'],
        ],
    ],
    'catalog_coupons' => [
        'name' => 'Action Codes',
        'legacy_path' => 'wms/catalogus/actiecodes',
        'group' => 'commerce',
        'table' => 'wms_catalog_coupons',
        'title_column' => 'name',
        'description' => 'Legacy action code overview and editor.',
        'legacy_tables' => ['actiecode'],
        'pages' => [
            'index' => ['name' => 'Action code overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit action code', 'type' => 'edit'],
        ],
    ],
    'orders' => [
        'name' => 'Orders',
        'legacy_path' => 'wms/orders',
        'group' => 'commerce',
        'table' => 'wms_orders',
        'title_column' => 'order_number',
        'description' => 'Legacy order overview, editor, documents, and cart detail pages.',
        'legacy_tables' => ['orders'],
        'pages' => [
            'index' => ['name' => 'Order overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit order', 'type' => 'edit'],
            'action' => ['name' => 'Order action', 'type' => 'utility', 'read_only' => true],
            'cartlist' => ['name' => 'Order item list', 'type' => 'utility', 'table' => 'wms_order_items', 'title_column' => 'name', 'read_only' => true, 'legacy_tables' => ['orderregels']],
            'carttotals' => ['name' => 'Order totals', 'type' => 'utility', 'read_only' => true],
            'downloadfactuur' => ['name' => 'Download invoice', 'type' => 'utility', 'read_only' => true],
            'downloadpakbon' => ['name' => 'Download packing slip', 'type' => 'utility', 'read_only' => true],
            'generateAdresSticker' => ['name' => 'Generate address sticker', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'order_delivery_dates' => [
        'name' => 'Delivery Dates',
        'legacy_path' => 'wms/orders/afleverdata',
        'group' => 'commerce',
        'table' => 'wms_delivery_dates',
        'title_column' => 'date',
        'description' => 'Legacy delivery date overview and editor.',
        'legacy_tables' => ['orderafleverdata', 'orderafleverdatadag', 'orderafleverdatadatum'],
        'pages' => [
            'index' => ['name' => 'Delivery date overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit delivery date', 'type' => 'edit'],
        ],
    ],
    'order_payment_methods' => [
        'name' => 'Payment Methods',
        'legacy_path' => 'wms/orders/betaalmethoden',
        'group' => 'commerce',
        'table' => 'wms_country_payment_methods',
        'title_column' => 'country_id',
        'description' => 'Legacy country payment method overview.',
        'legacy_tables' => ['isolandbetalingswijze'],
        'pages' => [
            'index' => ['name' => 'Payment method overview', 'type' => 'index'],
        ],
    ],
    'order_exports' => [
        'name' => 'Order Export',
        'legacy_path' => 'wms/orders/export',
        'group' => 'commerce',
        'table' => 'wms_orders',
        'title_column' => 'order_number',
        'read_only' => true,
        'description' => 'Legacy order export screens.',
        'legacy_tables' => ['orders'],
        'pages' => [
            'index' => ['name' => 'Order export overview', 'type' => 'utility', 'read_only' => true],
            'generateExcel' => ['name' => 'Generate order export', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'users' => [
        'name' => 'Users',
        'legacy_path' => 'wms/users',
        'group' => 'users',
        'table' => 'users',
        'title_column' => 'name',
        'read_only' => true,
        'description' => 'Legacy user overview and protected account screens.',
        'legacy_tables' => ['users'],
        'pages' => [
            'index' => ['name' => 'User overview', 'type' => 'index', 'read_only' => true],
            'edit' => ['name' => 'Edit user', 'type' => 'edit', 'read_only' => true],
            'resetPassword' => ['name' => 'Reset user password', 'type' => 'utility', 'read_only' => true],
            'wachtwoordvergeten' => ['name' => 'Forgotten password', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'user_categories' => [
        'name' => 'User Categories',
        'legacy_path' => 'wms/users/categorieen',
        'group' => 'users',
        'table' => 'wms_user_categories',
        'title_column' => 'name',
        'description' => 'Legacy user category overview and editor.',
        'legacy_tables' => ['usercategorieen'],
        'pages' => [
            'index' => ['name' => 'User category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit user category', 'type' => 'edit'],
        ],
    ],
    'locations' => [
        'name' => 'Locations',
        'legacy_path' => 'wms/vestigingen',
        'group' => 'locations',
        'table' => 'wms_locations',
        'title_column' => 'name',
        'description' => 'Legacy location overview and editor.',
        'legacy_tables' => ['vestiging'],
        'pages' => [
            'index' => ['name' => 'Location overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit location', 'type' => 'edit'],
            'editAfbeeldingen' => ['name' => 'Location images', 'type' => 'edit', 'table' => 'wms_location_images', 'title_column' => 'caption', 'legacy_tables' => ['vestigingafbeeldingen']],
            'editOpeningstijden' => ['name' => 'Location opening hours', 'type' => 'edit', 'table' => 'wms_location_opening_hours', 'title_column' => 'day', 'legacy_tables' => ['vestigingopeningstijd', 'vestigingspecialeopeningstijd']],
        ],
    ],
    'location_categories' => [
        'name' => 'Location Categories',
        'legacy_path' => 'wms/vestigingen/categorieen',
        'group' => 'locations',
        'table' => 'wms_location_categories',
        'title_column' => 'name',
        'description' => 'Legacy location category overview and editor.',
        'legacy_tables' => ['vestigingcategorie'],
        'pages' => [
            'index' => ['name' => 'Location category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit location category', 'type' => 'edit'],
        ],
    ],
    'redirects' => [
        'name' => 'Redirects',
        'legacy_path' => 'wms/redirect',
        'group' => 'seo',
        'table' => 'wms_redirects',
        'title_column' => 'source_path',
        'description' => 'Legacy redirect overview and editor.',
        'legacy_tables' => ['redirect'],
        'pages' => [
            'index' => ['name' => 'Redirect overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit redirect', 'type' => 'edit'],
        ],
    ],
    'urls' => [
        'name' => 'URLs',
        'legacy_path' => 'wms/url',
        'group' => 'seo',
        'table' => 'wms_urls',
        'title_column' => 'path',
        'description' => 'Legacy URL registry overview and editor.',
        'legacy_tables' => ['url'],
        'pages' => [
            'index' => ['name' => 'URL overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit URL', 'type' => 'edit'],
        ],
    ],
    'url_references' => [
        'name' => 'URL References',
        'legacy_path' => 'wms/urlverwijzingen',
        'group' => 'seo',
        'table' => 'wms_url_references',
        'title_column' => 'source_path',
        'description' => 'Legacy URL reference overview and editor.',
        'legacy_tables' => ['urlverwijzing'],
        'pages' => [
            'index' => ['name' => 'URL reference overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit URL reference', 'type' => 'edit'],
        ],
    ],
    'search_keywords' => [
        'name' => 'Search Keywords',
        'legacy_path' => 'wms/zoekwoorden',
        'group' => 'seo',
        'table' => 'wms_search_keywords',
        'title_column' => 'keyword',
        'description' => 'Legacy search keyword overview.',
        'legacy_tables' => ['zoekwoorden'],
        'pages' => [
            'index' => ['name' => 'Search keyword overview', 'type' => 'index'],
        ],
    ],
    'downloads' => [
        'name' => 'Downloads',
        'legacy_path' => 'wms/download',
        'group' => 'modules',
        'table' => 'wms_downloads',
        'title_column' => 'name',
        'description' => 'Legacy download overview and editor.',
        'legacy_tables' => ['downloads'],
        'pages' => [
            'index' => ['name' => 'Download overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit download', 'type' => 'edit'],
        ],
    ],
    'download_categories' => [
        'name' => 'Download Categories',
        'legacy_path' => 'wms/download/categorieen',
        'group' => 'modules',
        'table' => 'wms_download_categories',
        'title_column' => 'name',
        'description' => 'Legacy download category overview and editor.',
        'legacy_tables' => ['downloadcategorieen'],
        'pages' => [
            'index' => ['name' => 'Download category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit download category', 'type' => 'edit'],
        ],
    ],
    'mailing_contacts' => [
        'name' => 'Mailing Contacts',
        'legacy_path' => 'wms/mailingcontacten',
        'group' => 'modules',
        'table' => 'wms_mailing_contacts',
        'title_column' => 'email',
        'description' => 'Legacy mailing contact overview, editor, and sync screen.',
        'legacy_tables' => ['mailingcontacten'],
        'pages' => [
            'index' => ['name' => 'Mailing contact overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit mailing contact', 'type' => 'edit'],
            'sync' => ['name' => 'Sync mailing contacts', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'mailing_contact_categories' => [
        'name' => 'Mailing Contact Categories',
        'legacy_path' => 'wms/mailingcontacten/categorieen',
        'group' => 'modules',
        'table' => 'wms_mailing_contact_categories',
        'title_column' => 'name',
        'description' => 'Legacy mailing contact category overview and editor.',
        'legacy_tables' => ['mailingcontactcategorieen'],
        'pages' => [
            'index' => ['name' => 'Mailing contact category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit mailing contact category', 'type' => 'edit'],
        ],
    ],
    'mailing_contact_import' => [
        'name' => 'Mailing Contact Import',
        'legacy_path' => 'wms/mailingcontacten/import',
        'group' => 'modules',
        'table' => 'wms_mailing_contacts',
        'title_column' => 'email',
        'read_only' => true,
        'description' => 'Legacy mailing contact import screen.',
        'legacy_tables' => ['mailingcontacten'],
        'pages' => [
            'index' => ['name' => 'Import mailing contacts', 'type' => 'utility', 'read_only' => true],
            'import' => ['name' => 'Run mailing contact import', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'mailing_contact_export' => [
        'name' => 'Mailing Contact Export',
        'legacy_path' => 'wms/mailingcontacten/export',
        'group' => 'modules',
        'table' => 'wms_mailing_contacts',
        'title_column' => 'email',
        'read_only' => true,
        'description' => 'Legacy mailing contact export screen.',
        'legacy_tables' => ['mailingcontacten'],
        'pages' => [
            'index' => ['name' => 'Export mailing contacts', 'type' => 'utility', 'read_only' => true],
            'export' => ['name' => 'Run mailing contact export', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'module_manager' => [
        'name' => 'Module Manager',
        'legacy_path' => 'wms/module',
        'group' => 'configuration',
        'table' => 'cms_modules',
        'title_column' => 'name',
        'read_only' => true,
        'description' => 'Legacy module overview and protected editor.',
        'legacy_tables' => ['module'],
        'pages' => [
            'index' => ['name' => 'Module overview', 'type' => 'index', 'read_only' => true],
            'edit' => ['name' => 'Edit module', 'type' => 'edit', 'read_only' => true],
        ],
    ],
    'module_categories' => [
        'name' => 'Module Categories',
        'legacy_path' => 'wms/module/categorieen',
        'group' => 'configuration',
        'table' => 'wms_module_categories',
        'title_column' => 'name',
        'description' => 'Legacy module category overview and editor.',
        'legacy_tables' => ['modulecategorie'],
        'pages' => [
            'index' => ['name' => 'Module category overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit module category', 'type' => 'edit'],
        ],
    ],
    'roles' => [
        'name' => 'Roles and Permissions',
        'legacy_path' => 'wms/rbac',
        'group' => 'configuration',
        'table' => 'wms_roles',
        'title_column' => 'name',
        'description' => 'Legacy role and permission overview and editor.',
        'legacy_tables' => ['role', 'rechten'],
        'pages' => [
            'index' => ['name' => 'Role overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit role', 'type' => 'edit'],
        ],
    ],
    'rbac_log' => [
        'name' => 'RBAC Log',
        'legacy_path' => 'wms/rbac/log',
        'group' => 'configuration',
        'table' => 'wms_rbac_logs',
        'title_column' => 'action',
        'read_only' => true,
        'description' => 'Legacy RBAC log overview and detail screen.',
        'legacy_tables' => ['rbaclog'],
        'pages' => [
            'index' => ['name' => 'RBAC log overview', 'type' => 'index', 'read_only' => true],
            'view' => ['name' => 'View RBAC log entry', 'type' => 'utility', 'read_only' => true],
        ],
    ],
    'domains' => [
        'name' => 'Domains',
        'legacy_path' => 'wms/domein',
        'group' => 'configuration',
        'table' => 'wms_domains',
        'title_column' => 'host',
        'description' => 'Legacy domain overview and editor.',
        'legacy_tables' => ['domein'],
        'pages' => [
            'index' => ['name' => 'Domain overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit domain', 'type' => 'edit'],
        ],
    ],
    'countries' => [
        'name' => 'Countries',
        'legacy_path' => 'wms/isolanden',
        'group' => 'configuration',
        'table' => 'wms_countries',
        'title_column' => 'name',
        'description' => 'Legacy country overview and editor.',
        'legacy_tables' => ['isolanden'],
        'pages' => [
            'index' => ['name' => 'Country overview', 'type' => 'index'],
            'edit' => ['name' => 'Edit country', 'type' => 'edit'],
        ],
    ],
];

$rootPages = [
    'dashboard' => ['name' => 'Dashboard', 'type' => 'dashboard'],
    'firstLogin' => ['name' => 'First login', 'type' => 'utility'],
    'resetpass' => ['name' => 'Reset password', 'type' => 'utility'],
    'token' => ['name' => 'Token login', 'type' => 'utility'],
    'delete' => ['name' => 'Delete record', 'type' => 'utility'],
];

$legacyClasses = [
    'Actiecode' => 'catalog_coupons',
    'Banner' => 'banners',
    'BannerCategorie' => 'banner_categories',
    'CatalogusArtikel' => 'catalog_products',
    'CatalogusCategorie' => 'catalog_categories',
    'CatalogusMerk' => 'catalog_brands',
    'CatalogusPromotie' => 'catalog_promotions',
    'ContentCategorie' => 'content_categories',
    'ContentItem' => 'content_items',
    'Domein' => 'domains',
    'Download' => 'downloads',
    'DownloadCategorie' => 'download_categories',
    'Evenement' => 'events',
    'EvenementCategorie' => 'event_categories',
    'Faq' => 'faq_items',
    'FaqCategorie' => 'faq_categories',
    'Form' => 'forms',
    'FormCategorie' => 'form_categories',
    'Isoland' => 'countries',
    'MailingContact' => 'mailing_contacts',
    'MailingContacten' => 'mailing_contacts',
    'MailingContactCategorie' => 'mailing_contact_categories',
    'Module' => 'module_manager',
    'ModuleCategorie' => 'module_categories',
    'Order' => 'orders',
    'OrderAfleverData' => 'order_delivery_dates',
    'Radiogids' => 'radio_guides',
    'Radioprogramma' => 'radio_programs',
    'RBAC' => 'roles',
    'Redirect' => 'redirects',
    'Review' => 'catalog_reviews',
    'Role' => 'roles',
    'Slider' => 'sliders',
    'SliderCategorie' => 'slider_categories',
    'Url' => 'urls',
    'Urlverwijzing' => 'url_references',
    'User' => 'users',
    'UserCategorie' => 'user_categories',
    'Vacature' => 'vacancies',
    'VacatureCategorie' => 'vacancy_categories',
    'Vestiging' => 'locations',
    'VestigingCategorie' => 'location_categories',
    'Zoekwoorden' => 'search_keywords',
];

return [
    'groups' => $groups,
    'modules' => $modules,
    'screens' => $screens,
    'root_pages' => $rootPages,
    'legacy_classes' => $legacyClasses,
];
